FROM ubuntu:latest
LABEL maitainer="geela.balakrishna@gmail.com"
LABEL version="1.0.0"
RUN echo "Hi, i am run - 1"
RUN echo "Hi, i am run - 2"
RUN echo "Hi, i am run - 3"
CMD echo "Hi, i am CMD-1"
CMD echo "Hi, i am CMD-2"
CMD echo "Hi, i am CMD-3"




